# Generated by Django 5.1.6 on 2025-02-18 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profesor",
            old_name="profesion",
            new_name="materia",
        ),
    ]
