# Generated by Django 5.1.6 on 2025-02-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_profesion_profesor_materia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="estudiante",
            name="carrera",
            field=models.CharField(default="Sistemas", max_length=100),
        ),
    ]
